# Disabled banner, don't want to see the spring logo
spring:
  main:
    banner-mode: 'off'

# Media settings
# TODO: We can use ${...} placeholders, which will be replaced with
# environment variables. This is useful for customizing properties without
# changing the internal files (e.g. Docker/Rancher)
camera:
  front:
    audio:
      volume: 5
      codec: MP3
    video:
      resolution: 1920x1080
      fps: 60
      codec: MP4

  rear:
    audio:
      volume: 5
      codec: MP3
    video:
      resolution: 800x600
      fps: 30
      codec: THREEGP
